import os
import time
import random
print('Welcome to runner rpg simulator! this is completely unfinished, there is almost no content yet')
time.sleep(3)
print('Initalizing')
time.sleep(7)
aaroncon1 = (10)
attackdmg = (0)
poppet = ('Ÿ')
sparable = ('YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE')
# This is the useful not fully mastered code bits section, this describes incredibly useful commands that i often forget screen.getch() (every time you press a key it assigns this variable that value (not the actual value, the keyvalue, down is 256 i think for example, == curses.KEY_RIGHT: detects certan keys specifically, screen = curses.initscr() (uses the curses friendly screen) curses.cbreak() (no need to hit enter!)))
# planz: 1: make better skill checks and dungeons 2: make a city 3: make spells
charisma = (10)
will = (10)
health = (30)
strength = (10)
pasifist = ('Ÿ')
cunning = (10)
exploredone = (0)
yay = (0)
coins = (10)
hppotion = (0)
morality = (1)
hp = (10)
NOsnowdin = ('YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE')
transphorm = ('YEET')
debugcode = ('BeanTheBen')
buyn = ('False')
useful_text = ('‿ ')
os.system('clear')
leaveshop = ('False')
os.system('cls')
guardhp = random.randint(20,30)
yn1 = ('False')
sword = ('False')
healthpotion = ('')
exploredone = ('True')
exploredone2 = ('True')
y = ('y')
yeetus = ('yee')
while yeetus == 'yee':
  while exploredone2 == 'True':
    os.system('cls')
    os.system('clear')
    print('')
    print('')
    print('                              ----------        ')
    print('                            /            \      ')
    print('                           |   |     |    |     ')
    print('                           [              ]     ')
    print('                           ----------------     ')
    print('                           / |   |   |  |  \    ')
    print('                          |  |   |   |  |   |   ')
    print('                          |  |          |   |   ')
    print('------------------------------------------------')
    print('Hello! I am aaron the gel spider! I will be your tutorial guide!')
    time.sleep(2)
    print('This world is dark at times, you will need to know yourself before knowing your enemy, you have 5 stats, Strength, Cunning, Will, Brainpower, Charisma.')
    time.sleep(2)
    print('Your stats start low, but can get stronger!')
    advance = input('Hit enter to continue')
    aaroncon1 = ('0')
    exploredone = ('True')
    time.sleep(0.1)
    os.system('clear')
    os.system('cls')
    while aaroncon1 != '1':
      os.system('clear')
      os.system('cls')
      print('')
      print('')
      print('                              ----------        ')
      print('                            /            \      ')
      print('                           |    |      |  |     ')
      print('                           [       -      ]     ')
      print('                           ----------------     ')
      print('                           / |   |  |   |  \    ')
      print('                          |  |   |  |   |   |   ')
      print('                          |  |          |   |   ')
      print('------------------------------------------------')
      aaroncon1 = input('1: I get it 2: What are my stats? 3: who are you? 4: What race am i? 5: Just get to the fighting')
      if aaroncon1 == '1':
        print('Good, you seem to understand')
        exploredone = ('False')
        exploredone2 = ('False')
      if aaroncon1 == '2':
        os.system('cls')
        os.system('clear')
        print('')
        print('')
        print('                              ----------        ')
        print('                            /   |    |  \       ')
        print('                           |     ___     |      ')
        print('                           [             ]      ')
        print('                           ----------------     ')
        print('                           / |   |  |   |  \    ')
        print('                          |  |   |  |   |   |   ')
        print('                          |  |          |   |   ')
        print('------------------------------------------------')
        print('Your stats are all at 10 right now, most masters get to 50, gods and monsters have been known to get all the way to 60!')
        advance = input('Press enter to continue')
      if aaroncon1 == '3':
        os.system('cls')
        os.system('clear')
        print('')
        print('')
        print('                              ----------        ')
        print('                            /            \      ')
        print('                           |   |      |   |     ')
        print('                           [      ‿       ]    ')
        print('                           ----------------     ')
        print('                           / |   |   |  |  \    ')
        print('                          |  |   |   |  |   |   ')
        print('                          |  |          |   |   ')
        print('------------------------------------------------')
        print('Oh me? Im just a young gel spider who was told to help out the humans down here to get some allies!')
        time.sleep(2)
        print('Not that i require your friendliness or friendship')
        advance = input('Press enter to continue')
      if aaroncon1 == '4':
        time.sleep(2)
        os.system('cls')
        os.system('clear')
        print('')
        print('')
        print('                              ----------        ')
        print('                            /            \      ')
        print('                           |    |      |  |     ')
        print('                           [       _      ]     ')
        print('                           ----------------     ')
        print('                           / |   |   |  |  \    ')
        print('                          |  |   |   |  |   |   ')
        print('                          |  |          |   |   ')
        print('------------------------------------------------')
        print('You are a human, but knowing the volitale nature of spells down here you may not be for long.')
        advance = input('Press enter to continue')
      if aaroncon1 == '5':
        os.system('clear')
        os.system('cls')
        print('')
        print('')
        print('                              ----------        ')
        print('                            /   /      \ \      ')
        print('                           |    |      |  |     ')
        print('                           [       _      ]     ')
        print('                           ----------------     ')
        print('                           / |   |   |  |  \    ')
        print('                          |  |   |   |  |   |   ')
        print('                          |  |          |   |   ')
        print('------------------------------------------------')
        time.sleep(2)
        print('We do not fight down here, please be safe')
        advance = input('Hit enter to proceed')
  os.system('cls')
  os.system('clear')
  print('')
  print('')
  print('                              ----------        ')
  print('                            /            \      ')
  print('                           |   |     |    |     ')
  print('                           [      ‿       ]    ')
  print('                           ----------------     ')
  print('                           / |   |   |  |  \    ')
  print('                          |  |   |   |  |   |   ')
  print('                          |  |          |   |   ')
  print('------------------------------------------------')
  time.sleep(3)
  print('Let me show you around the underground')
  time.sleep(3)
  os.system('cls')
  os.system('clear')
  print('                /                                \           ')
  print('              _______________________________________        ')
  print('            /              |------|                    \     ')
  print('           |               |      |                   |      ')
  print('          /                |    0 |                     \    ')
  print('         |                 |      |                     |    ')
  print('        /                  |______|                      \   ')
  print('       |                                                  |  ')
  print('      /                                                   \  ')
  print('      |-------------------------------------------------|    ')
  print('     ///////////////////////////////////////////////////     ')
  print('    |                                                 |      ')
  print('    |-------------------------------------------------|      ')
  time.sleep(3)
  os.system('cls')
  os.system('clear')
  print('                /                                \           ')
  print('              _______________________________________        ')
  print('            /              |\----                      \     ')
  print('           |               ||    |                    |      ')
  print('          /                ||    |                      \    ')
  print('         |                 ||    |                      |    ')
  print('        /                  |/    |                       \   ')
  print('       |                                                  |  ')
  print('      /                                                   \  ')
  print('      |-------------------------------------------------|    ')
  print('     ///////////////////////////////////////////////////     ')
  print('    |                                                 |      ')
  print('    |-------------------------------------------------|      ')
  time.sleep(3)
  os.system('cls')
  os.system('clear')
  while exploredone == 'False':
    leaveshop == ('False')
    print('                /                                \           ')
    print('              _______________________________________        ')
    print('            /     |             |                       \     ')
    print('           |      |             |                      |      ')
    print('          / ______|             |_______________________ \    ')
    print('         |                                               |    ')
    print('        /                                                 \   ')
    print('       |                 @                                 |  ')
    print('      /                                                    \  ')
    print('            ______|             |_______________________      ')
    print('                  |             |                             ')
    print('    |             |             |                      |      ')
    print('    |-------------------------------------------------|      ')
    print('')
    print('')
    print('The @ is you, you can move about by typing N/E/S/W North East South and West')
    print(yn1)
    print(exploredone)
    waego = input('Where would you like to go?')
    wherego = waego.lower()
    if wherego == 'n':
      os.system('cls')
      os.system('clear')
      print('                /                                \           ')
      print('              _______________________________________        ')
      print('            /     |             |                       \     ')
      print('           |      |     @       |                      |      ')
      print('          / ______|             |_______________________ \    ')
      print('         |                                               |    ')
      print('        /                                                 \   ')
      print('       |                                                   |  ')
      print('      /                                                    \  ')
      print('            ______|             |_______________________      ')
      print('                  |             |                             ')
      print('    |             |             |                      |      ')
      print('    |-------------------------------------------------|      ')
      print('')
      print('')
      print('To the north there was a home!')
      time.sleep(2)
      os.system('cls')
      os.system('clear')
      print('')
      print('')
      print('                              ----------        ')
      print('                            /            \      ')
      print('                           |   |      |   |     ')
      print('                           [      ‿       ]     ')
      print('                           ----------------     ')
      print('                           / |   |   |  |  \    ')
      print('                          |  |   |   |  |   |   ')
      print('                          |  |          |   |   ')
      print('------------------------------------------------')
      print('This is my home! You can come in if you want! (y/n)')
      yn1 = input('y/n')
      if yn1 == y:
        home = 'True'
        exploredone = ('True')
        exploredone2 = ('True')
      else:
        os.system('cls')
        os.system('clear')
    if wherego == 'e':
      os.system('cls')
      os.system('clear')
      print('                /                                \           ')
      print('              _______________________________________        ')
      print('            /     |             |                       \     ')
      print('           |      |             |                      |      ')
      print('          / ______|             |_______________________ \    ')
      print('         |                                               |    ')
      print('        /                                                 \   ')
      print('       |                                    @              |  ')
      print('      /                                                    \  ')
      print('            ______|             |_______________________      ')
      print('                  |             |                             ')
      print('    |             |             |                      |      ')
      print('    |-------------------------------------------------|      ')
      time.sleep(2)
      os.system('cls')
      os.system('clear')
      print('')
      print('')
      print('                              ----------        ')
      print('                            /            \      ')
      print('                           |   |      |   |     ')
      print('                           [      ‿       ]     ')
      print('                           ----------------     ')
      print('                           / |   |   |  |  \    ')
      print('                          |  |   |   |  |   |   ')
      print('                          |  |          |   |   ')
      print('------------------------------------------------')
      print('')
      print('')
      print('There is a shop there! Do you wanna go in? (y/n)')
      goin = input('')
      goin = goin.lower()
      if goin == 'y':
        print('There is a kind shopkeeper at the door!')
        while leaveshop != 'y': 
          time.sleep(3)
          os.system('cls')
          os.system('clear')
          print('                                                                            ')
          print('    ±±                                                                      ')
          print('   /  \                                                                     ')
          print('   |  |                                                                     ')
          print('  _/__\_______       ___                                                    ')
          print('                    /   \           ||                                      ')
          print('                   | | | |          ||                                      ')
          print('                   | ‿   |         ||                                      ')
          print('                   \     /          ||                                      ')
          print('                    |  |            ||                                      ')
          print('                   /    \        --------                                   ')
          print('                / |      | \       |  |                  ___                ')
          print('               |  |      |  |      |  |                /     \              ')
          print('               |  |      |  |      |  |               | money |             ')
          print('               |  |      |  |      \  /               |  /    |             ')
          print('______________________________________________________|_/__\__|_____________')
          print('----------------------------------------------------------------------------')
          print('|                                                                          |')
          print('|                                                                          |')
          print('‿                                                                         ‿')
          print('                                                                            ')
          print('  O                                                                         ')
          print(' -|-                                                                        ')
          print(' / \                                                                        ')
          print('                                                                            ')
          print('                                                                            ')
          time.sleep(1)
          print('You have',coins,'coins.')
          buy4cash = input('They offer a sword, health potion, death protection poppet, and also ask if you may want to donate to orphans. 1: sword, 2: health potion, 3: poppet, 4: orphans 5: Leave')
          if buy4cash == '1':
            print('')
            print('')
            print('That will be 10 coins, do you want to buy it?')
            buyn = input('y/n')
            if buyn == 'y':
              if coins > 9:
                coins -= 10
                sword = ('True')
              else:
                print('You cannot afford that!')
          elif buy4cash == '2':
            print('')
            print('')
            print('That will be 4 coins, do you want to buy it?')
            buyn = input('y/n')
            if buyn == 'y':
              if coins < 4:
                print('You cannot afford that!')
              else:
                coins -= 4
                hppotion += 1
                print('Thank you!')
            else:
              print('Keep browsing.')
          elif buy4cash == '3':
            print('That is 8 coins')
            buyn = input('Do you want to buy this? (y/n)')
            if buyn == 'y':
              if coins < 8:
                print('You cannot afford that!')
              else:
                poppet = ('True')
                coins -= 8
                print('Enjoy your poppet!')
          elif buy4cash == '4':
            print('The minimum donation is 2 coins, do you want to buy this?')
            buyn = input('y/n')
            if buyn == 'y':
              if coins < 2:
                print('Sorry, you are too poor')
              else:
                coins -= 2
                print('Thank you for being such a wonderful person!')
                morality += 1
          elif buy4cash == '5':
            print('Come again!')
            os.system('cls')
            os.system('clear')
            leaveshop = ('y')
          else:
            print('Sorry we dont offer that.')
      else:
        os.system('cls')
        os.system('clear')
    if waego == 's':
      os.system('cls')
      os.system('clear')
      print('                /                                \           ')
      print('              _______________________________________        ')
      print('            /     |             |                       \     ')
      print('           |      |             |                      |      ')
      print('          / ______|             |_______________________ \    ')
      print('         |                                               |    ')
      print('        /                                                 \   ')
      print('       |                                                   |  ')
      print('      /                                                    \  ')
      print('            ______|             |_______________________      ')
      print('                  |      @      |                             ')
      print('    |             |             |                      |      ')
      print('    |-------------------------------------------------|      ')
      time.sleep(2)
      print('To the south there was a door!')
      time.sleep(2)
      os.system('cls')
      os.system('clear')
      time.sleep(1)
      print('')
      print('')
      print('                              ----------        ')
      print('                            /   /      \ \      ')
      print('                           |    |      |  |     ')
      print('                           [       _      ]     ')
      print('                           ----------------     ')
      print('                           / |   |   |  |  \    ')
      print('                          |  |   |   |  |   |   ')
      print('                          |  |          |   |   ')
      print('------------------------------------------------')
      time.sleep(2)
      print('Nobody has ever come back after going through, we dont know if they cannot open the door, or  if they have had a worse fate')
      tutorialend = input('Do you really want to go? I will go with if you go. (y/n)')
      tutorialend = tutorialend.lower()
      if tutorialend == 'y':
        yay = ('This')
      else:
        os.system('cls')
        os.system('clear')
    if waego == 'w':
      os.system('cls')
      os.system('clear')
      print('                /                                \           ')
      print('              _______________________________________        ')
      print('            /     |             |                       \     ')
      print('           |      |             |                      |      ')
      print('          / ______|             |_______________________ \    ')
      print('         |                                               |    ')
      print('        /                                                 \   ')
      print('       |      @                                            |  ')
      print('      /                                                    \  ')
      print('            ______|             |_______________________      ')
      print('                  |             |                             ')
      print('    |             |             |                      |      ')
      print('    |-------------------------------------------------|      ')
      time.sleep(2)
      print('You step in some muck!')
      time.sleep(2)
      os.system('cls')
      os.system('clear  ')
      time.sleep(2)
      print('                                 ')
      print('                                 ')
      print('            }  +                   ')
      print('        }   - _   =                   ')
      print('      }   (       | )                ')
      print('       9     \       |              ')
      print('_-_-_-_-_ _ _ _ _ _ _ _ _ _ _ _ _')
      time.sleep(2)
      os.system('cls')
      os.system('clear')
      print('                                 ')
      print('     ||    &    ^                    ')
      print('     ||  |  $   }  +                   ')
      print('     ||   }   - _   =                   ')
      print('     || }   (       | )                ')
      print('     |______  9     \       |              ')
      print('_-_-_-_-_ _ _ _ _ _ _ _ _ _ _ _ _')
      print('It begins climbing your leg, it gets darker and darker')
      time.sleep(2)
      print('It is absorbed into your flesh, you feel odd, as if you have a new limb or muscle you never felt before')
      time.sleep(6)
      os.system('cls')
      os.system('clear')
      transphorm = ('True')
    if yay == 'This':
      exploredone = ('True')
      os.system('cls')
      os.system('clear')
      NOsnowdin = ('True')
      while NOsnowdin == 'True':
        print('  /|\       /|\                                ')
        print(' /_|_\     /_|_\                               ')
        print('/--|--\   /--|--\                              ')
        print('   |         |                                 ')
        print('####   ########################################')
        print('#### @ ########################################')
        print('  /|\                                           ')
        print(' /_|_\                                          ')
        print('/--|--\                                         ')
        print('   |                                            ')
        wheredoyago = input('Hit 1 to go foward!')
        os.system('cls')
        os.system('clear')
        print('   /==========/ \   /==========/ \            ')
        print('  // |  |  |  \ \  // |  |  |  \ \            ')
        print('  /  |  |  |   \   /  |  |  |   \             ')
        print(' |   _____      | |     _____    |            ')
        print(' |  |- | -|     | |    |- | -|   |            ')
        print(' |     |0|      | |      |0|     |            ')
        print('  --------------   --------------             ')
        print('###### #######################################')
        print('##### @ ######################################')
        print('###### #######################################')
        print('  /==========/ \   /==========/ \             ')
        print(' // |  |  |  \ \  // |  |  |  \ \             ')
        print(' /  |  |  |   \   /  |  |  |   \              ')
        print('|   _____      | |     _____    |             ')
        print('|  |- | -|     | |    |- | -|   |             ')
        print('|              | |              |             ')
        print(' --------------   --------------              ')
        time.sleep(3)
        os.system('cls')
        os.system('clear')
        print('   /==========/ \   /==========/ \            ')
        print('  // |  |  |  \ \  // |  |  |  \ \            ')
        print('  /  |  |  |   \   /  |  |  |   \             ')
        print(' |   _____      | |     _____    |            ')
        print(' |  |- | -|     | |    |- | -|   |            ')
        print(' |     //       | |      \       |            ')
        print('  --------------   --------------             ')
        print('###### ## e ##################################')
        print('##### @ ## ###################################')
        print('###### #######################################')
        print('  /==========/ \   /==========/ \             ')
        print(' // |  |  |  \ \  // |  |  |  \ \             ')
        print(' /  |  |  |   \   /  |  |  |   \              ')
        print('|   _____      | |     _____    |             ')
        print('|  |- | -|     | |    |- | -|   |             ')
        print('|              | |              |             ')
        print(' --------------   --------------              ')
        time.sleep(3)
        os.system('cls')
        os.system('clear')
        print('')
        print('')
        print('                              ----------        ')
        print('                            /   /      \ \      ')
        print('                           |    |      |  |     ')
        print('                           [       _      ]     ')
        print('                           ----------------     ')
        print('                           / |   |   |  |  \    ')
        print('                          |  |   |   |  |   |   ')
        print('                          |  |          |   |   ')
        print('------------------------------------------------')
        time.sleep(1)
        print('')
        print('')
        print('Oh no! Thats an enemy, I guess i have to say, en garde!')
        time.sleep(2)
        while guardhp > 0:
          os.system('cls')
          os.system('clear')
          print('                                        O              ')
          print('                                    /\ /|\              ')
          print('                                    |_/ _              ')
          print('                                       / \             ')
          print('                                 _____/___\____________')
          print('                                                       ')
          print('            ___                                        ')
          print('           /   \                                       ')
          print('          | - - |                                      ')
          print('           \ - /                                       ')
          print('           /||\                                        ')
          print('          //||\\          ______   ______   _____      ')
          print('         // || \\        |  1   | |   2  | |  3  |     ')
          print('            ||           |FIGHT | |  ACT | | ITEM|     ')
          print('          /    \         |______| |______| |_____|     ')
          print('         /      \                                      ')
          print('________/________\_____________________________________')
          print('                                                       ')
          print('                                                       ')
          print('')
          print('')
          print('1: to fight (please dont) 2: to ACT, 3: to use an item')
          fite = input('What will you do?')
          if fite == '1':
            print('Tell me these numbers!')
            guardefence = random.randint(0,1)
            random1 = random.randint(1,9)
            random2 = random.randint(1,9)
            random3 = random.randint(1,9)
            random4 = random.randint(1,9)
            os.system('cls')
            os.system('clear')
            print('                                        O              ')
            print('                                    /\ /|\              ')
            print('                                    |_/ _              ')
            print('                                       / \             ')
            print('                                 _____/___\____________')
            print('                                                       ')
            print('            ___                                        ')
            print('           /   \                                       ')
            print('          | - - |                                      ')
            print('           \ - /                                       ')
            print('           /||\                                        ')
            print('          //||\\          ______   ______   _____      ')
            print('         // || \\        |  1   | |   2  | |  3  |     ')
            print('            ||           |FIGHT | |  ACT | | ITEM|     ')
            print('          /    \         |______| |______| |_____|     ')
            print('         /      \                                      ')
            print('________/________\_____________________________________')
            print('                                                       ')
            print('                                                       ')
            print('')
            print('')
            time.sleep(1)
            print(random1)
            os.system('cls')
            os.system('clear')
            print('                                        O              ')
            print('                                    /\ /|\              ')
            print('                                    |_/ _              ')
            print('                                       / \             ')
            print('                                 _____/___\____________')
            print('                                                       ')
            print('            ___                                        ')
            print('           /   \                                       ')
            print('          | - - |                                      ')
            print('           \ - /                                       ')
            print('           /||\                                        ')
            print('          //||\\          ______   ______   _____      ')
            print('         // || \\        |  1   | |   2  | |  3  |     ')
            print('            ||           |FIGHT | |  ACT | | ITEM|     ')
            print('          /    \         |______| |______| |_____|     ')
            print('         /      \                                      ')
            print('________/________\_____________________________________')
            print('                                                       ')
            print('                                                       ')
            print('')
            print('')
            print(random2)
            time.sleep(0.5)
            os.system('cls')
            os.system('clear')
            print('                                        O              ')
            print('                                    /\ /|\              ')
            print('                                    |_/ _              ')
            print('                                       / \             ')
            print('                                 _____/___\____________')
            print('                                                       ')
            print('            ___                                        ')
            print('           /   \                                       ')
            print('          | - - |                                      ')
            print('           \ - /                                       ')
            print('           /||\                                        ')
            print('          //||\\          ______   ______   _____      ')
            print('         // || \\        |  1   | |   2  | |  3  |     ')
            print('            ||           |FIGHT | |  ACT | | ITEM|     ')
            print('          /    \         |______| |______| |_____|     ')
            print('         /      \                                      ')
            print('________/________\_____________________________________')
            print('                                                       ')
            print('                                                       ')
            print('')
            print('')
            print('')
            print(random3)
            time.sleep(0.5)
            os.system('cls')
            os.system('clear')
            print('                                        O              ')
            print('                                    /\ /|\             ')
            print('                                    |_/ _              ')
            print('                                       / \             ')
            print('                                 _____/___\____________')
            print('                                                       ')
            print('            ___                                        ')
            print('           /   \                                       ')
            print('          | - - |                                      ')
            print('           \ - /                                       ')
            print('           /||\                                        ')
            print('          //||\\          ______   ______   _____      ')
            print('         // || \\        |  1   | |   2  | |  3  |     ')
            print('            ||           |FIGHT | |  ACT | | ITEM|     ')
            print('          /    \         |______| |______| |_____|     ')
            print('         /      \                                      ')
            print('________/________\_____________________________________')
            print('                                                       ')
            print('                                                       ')
            print('')
            print('')
            print(random4)
            time.sleep(1)
            os.system('cls')
            os.system('clear')
            print('                                        O              ')
            print('                                    /\ /|\              ')
            print('                                    |_/ _              ')
            print('                                       / \             ')
            print('                                 _____/___\____________')
            print('                                                       ')
            print('            ___                                        ')
            print('           /   \                                       ')
            print('          | - - |                                      ')
            print('           \ - /                                       ')
            print('           /||\                                        ')
            print('          //||\\          ______   ______   _____      ')
            print('         // || \\        |  1   | |   2  | |  3  |     ')
            print('            ||           |FIGHT | |  ACT | | ITEM|     ')
            print('          /    \         |______| |______| |_____|     ')
            print('         /      \                                      ')
            print('________/________\_____________________________________')
            print('                                                       ')
            print('                                                       ')
            print('')
            print('')
            attakdmg = (0)
            r1answer = input('What was the first number?')
            r2answer = input('What was the second number?')
            r3answer = input('What was the third number?')
            r4answer = input('What was the fourth number?')
            random1 = str(random1)
            random2 = str(random2)
            random3 = str(random3)
            random4 = str(random4)
            if r1answer == random1:
              attakdmg += 2
              korrekt = ('YEE')
            if r2answer == random2:
              attakdmg += 2
              korrekt = ('YEE')
            if r3answer == random3:
              attakdmg += 2
              korrekt = ('YEE')
            if r4answer == random4:
              attakdmg += 2
              korrekt = ('YEE')
            guardhp -= attakdmg
            print('Your attack did',attakdmg,'damage! The guard is at',guardhp,'health!')
            print('The guard attacks! How good are your reflexes?')
          takedmg = (8)
          random1 = random.randint(1,9)
          random2 = random.randint(1,9)
          random3 = random.randint(1,9)
          random4 = random.randint(1,9)
          print(random1)
          time.sleep(1)
          os.system('cls')
          os.system('clear')
          print(random2)
          time.sleep(1)
          os.system('cls')
          os.system('clear')
          print(random3)
          time.sleep(1)
          os.system('cls')
          os.system('clear')
          print(random4)
          time.sleep(1)
          os.system('cls')
          os.system('clear')
          print('                                        O              ')
          print('                                       /|\              ')
          print('                                    🗡  _              ')
          print('                                       / \             ')
          print('                                 _____/___\____________')
          print('                                                       ')
          print('            ___                                        ')
          print('           /   \                                       ')
          print('          | - - |                                      ')
          print('           \ - /                                       ')
          print('           /||\                                        ')
          print('          //||\\          ______   ______   _____      ')
          print('         // || \\        |  1   | |   2  | |  3  |     ')
          print('            ||           |FIGHT | |  ACT | | ITEM|     ')
          print('          /    \         |______| |______| |_____|     ')
          print('         /      \                                      ')
          print('________/________\_____________________________________')
          print('                                                       ')
          print('                                                       ')
          print('')
          print('')
          attakdmg = (0)
          r1answer = input('What was the first number?')
          r2answer = input('What was the second number?')
          r3answer = input('What was the third number?')
          r4answer = input('What was the fourth number?')
          random1 = str(random1)
          random2 = str(random2)
          random3 = str(random3)
          random4 = str(random4)
          if r1answer == random1:
            takedmg -= 2
          if r2answer == random2:
            takedmg -= 2
          if r3answer == random3:
            takedmg -= 2
          if r4answer == random4:
            takedmg -= 2
          health -= takedmg
          print('Oh no! the guard did',takedmg,'damage to you! You have',health,'health!')
          time.sleep(3)
          if health < 1:
            if poppet != "True":
              print('You died!')
              end()
            else:
              poppet = ('False')
              print('Your poppet revived you!')
              print('')
              print('')
              print('                              ----------        ')
              print('                            /   /      \ \      ')
              print('                           |    |      |  |     ')
              print('                           [       _      ]     ')
              print('                           ----------------     ')
              print('                           / |   |   |  |  \    ')
              print('                          |  |   |   |  |   |   ')
              print('                          |  |          |   |   ')
              print('------------------------------------------------')
              time.sleep(1)
              print('')
              print('')
              print('That was a close one!')
              time.sleep(3)
          if fite == '2':
            print('Do you 1: Chat  2: Throw water at it   3: Check')
            aaaa = input('')
            if aaaa == '1':
              os.system('cls')
              os.system('clear')
              print('                                        O              ')
              print('                                    /\ /|\              ')
              print('                                    |_/ _              ')
              print('                                       / \             ')
              print('                                 _____/___\____________')
              print('                                                       ')
              print('            ___                                        ')
              print('           /   \                                       ')
              print('          | - - |                                      ')
              print('           \ - /                                       ')
              print('           /||\                                        ')
              print('          //||\\          ______   ______   _____      ')
              print('         // || \\        |  1   | |   2  | |  3  |     ')
              print('            ||           |FIGHT | |  ACT | | ITEM|     ')
              print('          /    \         |______| |______| |_____|     ')
              print('         /      \                                      ')
              print('________/________\_____________________________________')
              print('                                                       ')
              print('                                                       ')
              print('')
              print('')
              time.sleep(1)
              print('He is utterly perswaded')
              time.sleep(3)
              if sparable == 'True':
                pasifist = ('True')
                guardhp = (0)
                os.system('cls')
                os.system('clear')
              sparable = ('True')
              os.system('cls')
              os.system('clear')
            if aaaa == '2':
              os.system('cls')
              os.system('clear')
              print('                                        O              ')
              print('                                    /\ /|\              ')
              print('                                    |_/ _              ')
              print('                                       / \             ')
              print('                                 _____/___\____________')
              print('                                                       ')
              print('            ___                                        ')
              print('           /   \                                       ')
              print('          | - - |                                      ')
              print('           \ - /                                       ')
              print('           /||\                                        ')
              print('          //||\\          ______   ______   _____      ')
              print('         // || \\        |  1   | |   2  | |  3  |     ')
              print('            ||           |FIGHT | |  ACT | | ITEM|     ')
              print('          /    \         |______| |______| |_____|     ')
              print('         /      \                                      ')
              print('________/________\_____________________________________')
              print('                                                       ')
              print('                                                       ')
              print('')
              print('')
              time.sleep(2)
              print('It gets angrier!')
              time.sleep(2)
              print('It smacks you!')
              time.sleep(2)
              health -= 1
            if aaaa == '3':
              print(guardhp,'is the guards health')
              print('Without blocking you take 8 damage')
              print('Wondering why he is fighting you')
          if fite == '3':
            if healthpotion == '':
              print('U got none of teh itemz')
            else:
              print('You have a health potion')
              print('Do u wan use?')
              wan_ues = input('y/n')
              wan_ues = wan_ues.lower()
              if wan_ues == 'y':
                healthpotion -= 1
                health += 10
          if guardhp < 1:
            if pasifist != 'True':
              print('You killed it!')
              strength += 1
              print('You got 10 gold, you got stronger!')
              coins += 10
              morality -= 1
            else:
              print('You spared it!')
              print('You got more charismatic! You got 5 coins from the guard as he apoligises.')
              charisma += 1
              coins += 5
        print('You emerge into a nice city')
        time.sleep(3)
        os.system('cls')
        os.system('clear')
        print('        ______________                  ')
        print('        \             /                 ')
        print('/--------\           /-----------------/')
        print('_________  _________  __________________')
        print('   |      |  |      |  |              | ')
        print('   |      |         |  |              | ')
        print('   |      |  |   _  |  |              | ')
        print('---|------|         |--|----------------')
        print('   |      |  -      |  |              | ')
        print('   |      |         |  |              | ')
        print('   |      |   |     |  |              | ')
        print('________  ___________  _________________')
        print('######## /////////// \ #################')
        print('####### /\\\\\\\\\\\\\\ ################')
        print('####### _______________ ################')
        print('##### @ ################################')
        print('###### #################################')
        time.sleep(3)
        os.system('cls')
        os.system('clear')
        print('        ______________                  ')
        print('        \             /                 ')
        print('/--------\           /-----------------/')
        print('_________  _________  __________________')
        print('   |      |  |      |  |              | ')
        print('   |      |         |  |              | ')
        print('   |      |  |   _  |  |              | ')
        print('---|------|         |--|----------------')
        print('   |      |  -      |  |              | ')
        print('   |      |         |  |              | ')
        print('   |      |   |     |  |              | ')
        print('________  ___________  _________________')
        print('######## /////////// \ #################')
        print('####### /\\\\\\\\\\\\\\ ################')
        print('####### _______________ ################')
        print('############ @ #########################')
        print('############# ##########################')
        time.sleep(3)
        os.system('cls')
        os.system('clear')
        print('        ______________                  ')
        print('        \             /                 ')
        print('/--------\           /-----------------/')
        print('_________  _________  __________________')
        print('   |      |  |      |  |              | ')
        print('   |      |         |  |              | ')
        print('   |      |  |   _  |  |              | ')
        print('---|------|         |--|----------------')
        print('   |      |  -      |  |              | ')
        print('   |      |         |  |              | ')
        print('   |      |   |     |  |              | ')
        print('________  ___________  _________________')
        print('######## /////////// \ #################')
        print('####### /\\\\\\\\\\\\\\ ################')
        print('####### _______________ ################')
        print('############################# @ ########')
        print('############################## #########')
        time.sleep(3)
        os.system('cls')
        os.system('clear')
        print('                                                    ')
        print('### @ ####################                          ')
        print('#### #####################                          ')
        print('                       ###                          ')
        print(' __________            ###                          ')
        print('|\_\_\_\_\_\##############                          ')
        print('||---------|##############                          ')
        print('|/_/_/_/_/_/           ###                          ')
        print('                       ###                          ')
        print('                       ###                          ')
        print('                       ###      .-----.             ')
        print('                       ###      |\    |             ')
        print('                       ###      .-----.             ')
        print('                       ###      | |-| |             ')
        print('                       ###      |     |             ')
        print('                       ###      |     |             ')
        print('                       ###      |     |             ')
        print('                       ###      |     |             ')
        print('                       ###      |____ |             ')
        print('                       ###      || 0| |             ')
        print('                       ###      |_____|             ')
        print('                       ###      |/////|             ')

        
        

              
